=== viccpp/__vic/doc/document.dtd
<!ELEMENT document (title, (annotation | chapter | TODO)*)>
<!ATTLIST document
    xml:lang CDATA #REQUIRED
    version CDATA #IMPLIED
    status  (Release | Draft) #IMPLIED>

<!ENTITY % section-content "p | list | code-block | tty | note | precondition | postcondition | invariant | synopsis | TODO">
<!ENTITY % text-with-markup "#PCDATA | tt | u | b | nt | link | xref | badge">

<!ELEMENT chapter (title, (chapter | section | %section-content;)*)>
<!ATTLIST chapter
    xml:id ID #REQUIRED>

<!ELEMENT section (title, (%section-content;)*)>

<!ELEMENT title (%text-with-markup;)*>

<!ELEMENT tty        (#PCDATA | nt)*>
<!ELEMENT code-block (#PCDATA | nt)*>
<!ATTLIST code-block
    lang CDATA #IMPLIED>

<!ELEMENT p (%text-with-markup;)*>

<!ELEMENT synopsis (prototype+, (p | precondition | postcondition | invariant | note | list)*)>

<!ELEMENT prototype (#PCDATA | nt | badge)*>

<!ELEMENT tt (#PCDATA | nt)*>

<!ELEMENT u (#PCDATA | b | nt)*>

<!ELEMENT b (#PCDATA | u | nt)*>

<!ELEMENT nt (#PCDATA)>

<!ELEMENT link (#PCDATA)>
<!ATTLIST link
    href CDATA #IMPLIED>

<!ELEMENT xref EMPTY>
<!ATTLIST xref
    to IDREF #REQUIRED>

<!ELEMENT list (item+)>
<!ATTLIST list
    style (numbered | bulleted | nomarks) #REQUIRED>

<!ELEMENT item (%text-with-markup; | %section-content;)*>

<!ELEMENT note (%text-with-markup; | %section-content;)*>
<!ELEMENT precondition (%text-with-markup; | %section-content;)*>
<!ELEMENT postcondition (%text-with-markup; | %section-content;)*>
<!ELEMENT invariant (%text-with-markup; | %section-content;)*>

<!ELEMENT annotation (documentation*)>
<!ELEMENT documentation (#PCDATA)> <!-- ANY ? -->

<!ELEMENT badge (#PCDATA)>

<!ELEMENT TODO (#PCDATA)>

=== viccpp/__vic/doc/ru/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../html.xsl"?>
<!DOCTYPE document SYSTEM "../document.dtd" [
    <!ENTITY why SYSTEM "why.xml">
    <!ENTITY general SYSTEM "general.xml">
    <!ENTITY build SYSTEM "build.xml">
    <!ENTITY defs.h SYSTEM "defs.h.xml">
    <!ENTITY algorithm.h SYSTEM "algorithm.h.xml">
    <!ENTITY ascii.h SYSTEM "ascii.h.xml">
    <!ENTITY ascii_string.h SYSTEM "ascii_string.h.xml">
    <!ENTITY base16.h SYSTEM "base16.h.xml">
    <!ENTITY base64.h SYSTEM "base64.h.xml">
    <!ENTITY bin_file.h SYSTEM "bin_file.h.xml">
    <!ENTITY bits.h SYSTEM "bits.h.xml">
    <!ENTITY bounded_vector.h SYSTEM "bounded_vector.h.xml">
    <!ENTITY date_time.h SYSTEM "date_time.h.xml">
    <!ENTITY endian.h SYSTEM "endian.h.xml">
    <!ENTITY error.h SYSTEM "error.h.xml">
    <!ENTITY fs.h SYSTEM "fs.h.xml">
    <!ENTITY iterator.h SYSTEM "iterator.h.xml">
    <!ENTITY logger.h SYSTEM "logger.h.xml">
    <!ENTITY memory.h SYSTEM "memory.h.xml">
    <!ENTITY mutex.h SYSTEM "mutex.h.xml">
    <!ENTITY packon.h SYSTEM "packon.h.xml">
    <!ENTITY readonly_cstring.h SYSTEM "readonly_cstring.h.xml">
    <!ENTITY set_of_chars.h SYSTEM "set_of_chars.h.xml">
    <!ENTITY sreaders SYSTEM "sreaders.xml">
    <!ENTITY stdint.h SYSTEM "stdint.h.xml">
    <!ENTITY stdio_file.h SYSTEM "stdio_file.h.xml">
    <!ENTITY str2num.h SYSTEM "str2num.h.xml">
    <!ENTITY string_buffer.h SYSTEM "string_buffer.h.xml">
    <!ENTITY string_ref.h SYSTEM "string_ref.h.xml">
    <!ENTITY string_utils.h SYSTEM "string_utils.h.xml">
    <!ENTITY swriters SYSTEM "swriters.xml">
    <!ENTITY tchar.h SYSTEM "tchar.h.xml">
    <!ENTITY thread.h SYSTEM "thread.h.xml">
    <!ENTITY throw_errno.h SYSTEM "throw_errno.h.xml">
    <!ENTITY to_text.h SYSTEM "to_text.h.xml">
    <!ENTITY type_traits.h SYSTEM "type_traits.h.xml">
    <!ENTITY unicode.h SYSTEM "unicode.h.xml">
    <!ENTITY utf16.defs.h SYSTEM "utf16.defs.h.xml">
    <!ENTITY utf16.exceptions.h SYSTEM "utf16.exceptions.h.xml">
    <!ENTITY utf16.read_result.h SYSTEM "utf16.read_result.h.xml">
    <!ENTITY utf16.reader.h SYSTEM "utf16.reader.h.xml">
    <!ENTITY utf16.status.h SYSTEM "utf16.status.h.xml">
    <!ENTITY utf16.writer.h SYSTEM "utf16.writer.h.xml">
    <!ENTITY utf8.exceptions.h SYSTEM "utf8.exceptions.h.xml">
    <!ENTITY utf8.read_result.h SYSTEM "utf8.read_result.h.xml">
    <!ENTITY utf8.reader.h SYSTEM "utf8.reader.h.xml">
    <!ENTITY utf8.status.h SYSTEM "utf8.status.h.xml">
    <!ENTITY utf8.writer.h SYSTEM "utf8.writer.h.xml">
    <!ENTITY waitable_event.h SYSTEM "waitable_event.h.xml">
    <!ENTITY windows.bitmap.h SYSTEM "windows.bitmap.h.xml">
    <!ENTITY windows.critical_section.h SYSTEM "windows.critical_section.h.xml">
    <!ENTITY windows.dc.h SYSTEM "windows.dc.h.xml">
    <!ENTITY windows.error.h SYSTEM "windows.error.h.xml">
    <!ENTITY windows.event.h SYSTEM "windows.event.h.xml">
    <!ENTITY windows.find_file.h SYSTEM "windows.find_file.h.xml">
    <!ENTITY windows.handle.h SYSTEM "windows.handle.h.xml">
    <!ENTITY windows.shadow_dc.h SYSTEM "windows.shadow_dc.h.xml">
    <!ENTITY windows.throw_last_error.h SYSTEM "windows.throw_last_error.h.xml">
    <!ENTITY windows.wait_cursor.h SYSTEM "windows.wait_cursor.h.xml">
    <!ENTITY windows.wchar.h SYSTEM "windows.wchar.h.xml">
    <!ENTITY windows.window.h SYSTEM "windows.window.h.xml">
]>
<document xml:lang="ru" version="1.0" status="Draft">
<title>__vic's C++ library (Windows)</title>

<annotation><documentation><![CDATA[
Тэги, используемые для форматирования документа:

document
    Корневой элемент. Атрибуты:
        * lang - язык документа,
        * version - например "1.0",
        * status - "Release" или "Draft".
chapter
    Глава. Попадает в оглавление. Главы могут вкладываться друг в друга. Атрибут
    "xml:id" задаёт уникальный ID главы.
section
    Секция текста. Содержится в главе и не попадает в оглавление.
title
    Заголовок документа, главы или секции. Обязателен. Должен быть первым
    элементом.
p
    Абзац.
list
    Список. Обязательный атрибут style задаёт тип списка:
        * numbered - нумерованный,
        * bulleted - маркированный,
        * nomarks  - без маркировки.
    Каждый элемент помещается в <item>.
code-block
    Прямоугольный блок текста с кодом. Атрибут lang указывает используемый язык.
    Исходное форматирование сохраняется при показе.
tty
    Прямоугольный блок текста с выводом текстового терминала.
    Исходное форматирование сохраняется при показе.
note
    Замечание.
b
    Выделение текста жирным.
u
    Подчеркнутый текст.
tt
    Моноширинный текст для элементов кода, имён файлов и т.п.
nt
    "Нетерминальный символ" (из теории формальных языков). Текст-placeholder,
    который нужно заменить на что-то перед использованием.
link
    Гиперссылка. URL, либо текст + URL в атрибуте href.
xref
    Внутрення ссылка на главу документа. Атрибут to указывает ID главы.
synopsis
    Справка по функции, типу и т.п. Прототип функции или объявление типа
    заключается в <prototype>. Исходное форматирование в нём сохраняется
    при показе. Текстовое описание помещается в <p>. Предусловие помещается
    в <precondition>, постусловие - в <postcondition>, инвариант - в
    <invariant>.
precondition
    Предусловие. Часть <synopsis>.
postcondition
    Постусловие. Часть <synopsis>.
invariant
    Инвариант. Часть <synopsis>.
badge
    Небольшой значёк-пометка на слове или строке.
TODO
    Пометка TODO для редактора документа.
]]></documentation></annotation>

<chapter xml:id="intro">
<title>Введение</title>
&why;
&general;
</chapter>

<chapter xml:id="components-reference">
<title>Описание компонентов библиотеки</title>
&defs.h;
&algorithm.h;
&ascii.h;
&ascii_string.h;
&base16.h;
&base64.h;
&bin_file.h;
&bits.h;
&bounded_vector.h;
&date_time.h;
&endian.h;
&error.h;
&fs.h;
&iterator.h;
&logger.h;
&memory.h;
&mutex.h;
&packon.h;
&readonly_cstring.h;
&set_of_chars.h;
&stdint.h;
&stdio_file.h;
&str2num.h;
&string_buffer.h;
&string_ref.h;
&string_utils.h;
&tchar.h;
&thread.h;
&throw_errno.h;
&to_text.h;
&type_traits.h;
&unicode.h;
&utf8.status.h;
&utf8.exceptions.h;
&utf8.read_result.h;
&utf8.reader.h;
&utf8.writer.h;
&utf16.defs.h;
&utf16.status.h;
&utf16.exceptions.h;
&utf16.read_result.h;
&utf16.reader.h;
&utf16.writer.h;
&waitable_event.h;
&windows.bitmap.h;
&windows.critical_section.h;
&windows.dc.h;
&windows.error.h;
&windows.event.h;
&windows.find_file.h;
&windows.handle.h;
&windows.shadow_dc.h;
&windows.throw_last_error.h;
&windows.wait_cursor.h;
&windows.wchar.h;
&windows.window.h;
</chapter>

&sreaders;
&swriters;

<chapter xml:id="build">
<title>Сборка и установка</title>
&build;
</chapter>

</document>

=== viccpp/__vic/doc/en/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../html.xsl"?>
<!DOCTYPE document SYSTEM "../document.dtd" [
    <!ENTITY why SYSTEM "why.xml">
    <!ENTITY general SYSTEM "general.xml">
    <!ENTITY build SYSTEM "build.xml">
    <!ENTITY defs.h SYSTEM "defs.h.xml">
    <!ENTITY algorithm.h SYSTEM "algorithm.h.xml">
    <!ENTITY ascii.h SYSTEM "ascii.h.xml">
    <!ENTITY ascii_string.h SYSTEM "ascii_string.h.xml">
    <!ENTITY base16.h SYSTEM "base16.h.xml">
    <!ENTITY base64.h SYSTEM "base64.h.xml">
    <!ENTITY bin_file.h SYSTEM "bin_file.h.xml">
    <!ENTITY bits.h SYSTEM "bits.h.xml">
    <!ENTITY bounded_vector.h SYSTEM "bounded_vector.h.xml">
    <!ENTITY date_time.h SYSTEM "date_time.h.xml">
    <!ENTITY endian.h SYSTEM "endian.h.xml">
    <!ENTITY error.h SYSTEM "error.h.xml">
    <!ENTITY iterator.h SYSTEM "iterator.h.xml">
    <!ENTITY logger.h SYSTEM "logger.h.xml">
    <!ENTITY memory.h SYSTEM "memory.h.xml">
    <!ENTITY readers SYSTEM "readers.xml">
    <!ENTITY readonly_cstring.h SYSTEM "readonly_cstring.h.xml">
    <!ENTITY set_of_chars.h SYSTEM "set_of_chars.h.xml">
    <!ENTITY stdint.h SYSTEM "stdint.h.xml">
    <!ENTITY stdio_file.h SYSTEM "stdio_file.h.xml">
    <!ENTITY str2num.h SYSTEM "str2num.h.xml">
    <!ENTITY string_buffer.h SYSTEM "string_buffer.h.xml">
    <!ENTITY string_ref.h SYSTEM "string_ref.h.xml">
    <!ENTITY string_utils.h SYSTEM "string_utils.h.xml">
    <!ENTITY tchar.h SYSTEM "tchar.h.xml">
    <!ENTITY throw_errno.h SYSTEM "throw_errno.h.xml">
    <!ENTITY to_text.h SYSTEM "to_text.h.xml">
    <!ENTITY type_traits.h SYSTEM "type_traits.h.xml">
    <!ENTITY unicode.h SYSTEM "unicode.h.xml">
    <!ENTITY utf16.defs.h SYSTEM "utf16.defs.h.xml">
    <!ENTITY utf16.exceptions.h SYSTEM "utf16.exceptions.h.xml">
    <!ENTITY utf16.reader.h SYSTEM "utf16.reader.h.xml">
    <!ENTITY utf16.status.h SYSTEM "utf16.status.h.xml">
    <!ENTITY utf16.writer.h SYSTEM "utf16.writer.h.xml">
    <!ENTITY utf8.exceptions.h SYSTEM "utf8.exceptions.h.xml">
    <!ENTITY utf8.reader.h SYSTEM "utf8.reader.h.xml">
    <!ENTITY utf8.status.h SYSTEM "utf8.status.h.xml">
    <!ENTITY utf8.writer.h SYSTEM "utf8.writer.h.xml">
    <!ENTITY waitable_event.h SYSTEM "waitable_event.h.xml">
    <!ENTITY writers SYSTEM "writers.xml">
]>
<document xml:lang="en" version="1.0" status="Draft">
<title>__vic's C++ library</title>

<annotation><documentation><![CDATA[
Tags used to format this document:

document
    Root element. Attributes:
        * lang - document's language,
        * version - like "1.0",
        * status - "Release" or "Draft".
chapter
    A chapter. An entry of the table of contents (TOC). Can be nested to each
    other. "xml:id" attribute specifies the unique chapter ID.
section
    A section of text. Included in a chapter. Not a part of TOC.
title
    Title of the document, chapter or section. Required. Must be the first
    element.
p
    A paragraph.
list
    List. Required attribute "style" has one of following values:
        * numbered - numbered,
        * bulleted - bulleted,
        * nomarks  - without any bullet marks.
    Every list element is placed to <item>.
code-block
    Rectangular text block with the code. "lang" attribute specifies used
    language. Formatting is preserved.
tty
    Rectangular text block with the text terminal output. Formatting is
    preserved.
note
    A note.
b
    Specifies bold text.
u
    Specifies underlined text.
tt
    Monospace text for elements of code, filenames, etc.
nt
    "Nonterminal symbol" (formal grammar term). Placeholder text which must be
    replaced by something before usage.
link
    A hyperlink. Either URL or text + URL in the "href" attribute.
xref
    Cross-reference to the document chapter. "to" attribute specifies the
    chapter ID.
synopsis
    Reference to component (function, type, etc). Function prototype or type
    definition is enclosed in <prototype>. Formatting is preserved.
    Text description is enclosed in <p>. Precodition is encloded in
    <precondition>, postcondition - in <postcondition>, invariant - in
    <invariant>.
precondition
    Precondition. Part of <synopsis>.
postcondition
    Postcondition. Part of <synopsis>.
invariant
    Invariant. Part of <synopsis>.
badge
    Tiny marker on a word or on a line.
TODO
    TODO-marker for the editor of this document.
]]></documentation></annotation>

<chapter xml:id="intro">
<title>Introduction</title>
&why;
&general;
</chapter>

<chapter xml:id="components-reference">
<title>Library components reference</title>
&defs.h;
&algorithm.h;
&ascii.h;
&ascii_string.h;
&base16.h;
&base64.h;
&bin_file.h;
&bits.h;
&bounded_vector.h;
&date_time.h;
&endian.h;
&error.h;
&iterator.h;
&logger.h;
&memory.h;
&readers;
&readonly_cstring.h;
&set_of_chars.h;
&stdint.h;
&stdio_file.h;
&str2num.h;
&string_buffer.h;
&string_ref.h;
&string_utils.h;
&tchar.h;
&throw_errno.h;
&to_text.h;
&type_traits.h;
&unicode.h;
&utf8.status.h;
&utf8.exceptions.h;
&utf8.reader.h;
&utf8.writer.h;
&utf16.defs.h;
&utf16.status.h;
&utf16.exceptions.h;
&utf16.reader.h;
&utf16.writer.h;
&waitable_event.h;
&writers;
</chapter>

<chapter xml:id="build">
<title>Build and install</title>
&build;
</chapter>

</document>
